### ISSUE TITLE
URGEN - Issue on Turkish devices crashing the application

### ISSUE THREAD

**Issue by hajimeku** [bugsnag/bugsnag-unity#537]
### Describe the bug
com.bugsnag.android.BreadcrumbType.NAVİGATİON
    java.lang.IllegalArgumentException: No enum constant com.bugsnag.android.BreadcrumbType.NAVİGATİON
        at java.lang.Enum.valueOf(Enum.java:257)
        at com.bugsnag.android.BreadcrumbType.valueOf(Unknown Source:2)
        at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
        at com.unity3d.player.UnityPlayer.access$300(Unknown Source:0)
        at com.unity3d.player.UnityPlayer$e$1.handleMessage(Unknown Source:95)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:214)
        at com.unity3d.player.UnityPlayer$e.run(Unknown Source:20)
      at UnityEngine.AndroidJNISafe.CheckException () [0x00000] in <00000000000000000000000000000000>:0
      at UnityEngine.AndroidJNISafe.CallStaticObjectMethod (System.IntPtr clazz, System.IntPtr methodID, UnityEngine.jvalue[] args) [0x00000] in <00000000000000000000000000000000>:0
      at UnityEngine.AndroidJavaObject._CallStatic[Retur

On all turkish devices our game crashes now because somewhere in the code you do TO UPPER com.bugsnag.android.BreadcrumbType.NAVİGATİON
Notice the NAVİGATİON is written with Turkish special i.

This happens somewhere in your code doing ToUpper or ToLower without culturally irrelevant parsing

### Steps to reproduce
1. Set your phone in the Turkish language
2. Boot an App with the Bugsnag plugin in it.

### Environment
* Bugsnag version:6.3.0
* Unity version:2020.3.24f
* Android
* simulator/emulator or physical device:
* Initializing bugsnag via code:
* Player Settings:
    * Scripting backend (Mono or IL2CPP):
    * API compatibility level for .NET:
    * Stack Trace level for all error types (None/ScriptOnly/Full):

**Comment by hajimeku** [comment]
You can fix it here:
https://github.com/bugsnag/bugsnag-unity/blob/next/src/BugsnagUnity/Native/Android/NativeBreadcrumb.cs

You need to ToUpper CultureInfo.InvariantCulture

**Comment by hajimeku** [comment]
You have the same issue here:
        private void SetSeverity(Severity severity)
        {
            var nativeSeverity = new AndroidJavaClass("com.bugsnag.android.Severity").GetStatic<AndroidJavaObject>(severity.ToString().ToUpper());
            NativePointer.Call("setSeverity",nativeSeverity);
        }

**Comment by xander-jones** [comment]
Hey @hajimeku, thanks for reporting the issue. We'll keep you posted with updates on a fix here.

**Comment by xander-jones** [comment]
A fix for this has been released in https://github.com/bugsnag/bugsnag-unity/releases/tag/v6.3.1, thanks for raising the issue!
